RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 300
CHUNK_OVERLAP: 30
DATA_PATH: '/Users/konstantinbaltsat/app/CHATS'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_TYPE: 'mistral'
# MODEL_TYPE: 'llama'
MODEL_BIN_PATH: 'models/mistral-7b-instruct-v0.1.Q5_K_M.gguf'
# MODEL_BIN_PATH: 'models/llama-2-7b.Q5_K_M.gguf'

EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
MAX_NEW_TOKENS: 4096
CONTEXT_LENGTH: 4096
TEMPERATURE: 0.00

DEFAULT_PROMPT: >
  .