# First step: set up datastax VectorDB
# Download the secure connect bundle and token from the DataStax Astra UI
# Download connection token from the DataStax Astra UI

import json
import os

from cassandra.auth import PlainTextAuthProvider
from cassandra.cluster import Cluster

# This secure connect bundle is autogenerated when you donwload your SCB,
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': 'secure-connect-temp-db.zip'
}

# This token json file is autogenerated when you donwload your token,
# if yours is different update the file name below
with open(os.getenv("TOKEN_FILE")) as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

row = session.execute("select release_version from system.local").one()
if row:
    print(row[0])
else:
    print("An error occurred.")